#!/usr/bin/env bash

# Find all staged Python files, and exit early if there aren't any.
PYTHON_FILES=$(git diff --name-only --cached --diff-filter=AM | grep --color=never '.py$')
if [ -z "${PYTHON_FILES}" ]; then
  echo 'no staged python files'
  exit 0
fi

# Verify that black is installed; if not, warn and exit.
if ! command -v black >/dev/null; then
  echo 'black not on path; can not format. Please install black:'
  echo '    pip install black'
  exit 2
fi

# Check for unstaged changes to files in the index.
CHANGED_FILES=$(git diff --name-only "${PYTHON_FILES[@]}")
if [ -n "${CHANGED_FILES}" ]; then
  echo 'You have unstaged changes to some files in your commit; skipping '
  echo 'auto-format. Please stage, stash, or revert these changes. You may '
  echo 'find `git stash -k` helpful here.'
  echo 'Files with unstaged changes:' "${CHANGED_FILES[@]}"
  exit 1
fi

# Format all staged files, then exit with an error code if any have uncommitted
# changes.
echo 'Formatting staged Python files . . .'

black "${PYTHON_FILES[@]}" --exclude=font_pb2.py

CHANGED_FILES=$(git diff --name-only "${PYTHON_FILES[@]}")
if [ -n "${CHANGED_FILES}" ]; then
  echo 'Reformatted staged files. Please review and stage the changes.'
  echo 'Files updated: ' "${CHANGED_FILES[@]}"
  exit 1
else
  exit 0
fi
