language: python

# Black requires Python 3.6, so we test in Python 3.5 and lint in Python 3.6
matrix:
  include:
  - name: "Python 3.5 Test"
    python: 3.5
    env: PYTHON_VERSION=3.5 NAME="TEST"
  - name: "Python 3.6 Lint"
    python: 3.6
    env: PYTHON_VERSION=3.6 NAME="LINT"

install:
  - if [[ $NAME == TEST ]]; then make venv; fi
  - if [[ $NAME == LINT ]]; then make develop; fi
  - pip freeze

script:
  - if [[ $NAME == TEST ]]; then make test; fi
  - if [[ $NAME == LINT ]]; then make lint; fi

jobs:
  include:
    - stage: install
      script: pip install mkdocs
      on:
        branch: master
    - stage: before_deploy
      script: mkdocs build --verbose --clean --strict; fi
      on:
        branch: master
    - stage: deploy
      provider: pages
      skip_cleanup: true
      github_token: $github_token
      local_dir: site
      on:
        branch: master
