site_name: Knead
repo_url: https://github.com/font-bakers/knead
nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - User Guide: user-guide.md
    - Developer Guide: developer-guide.md
    - Contributing: contributing.md
    - About:
      - License: https://github.com/font-bakers/knead/blob/master/LICENSE
theme: readthedocs
